import os
import re
import sys
import markdown
from playwright.sync_api import sync_playwright
from playwright_stealth import Stealth

# TODO: Verify or update these selectors if Naver Premium Content layout changes.
NEW_POST_URL = "https://studio.premium.naver.com/post/write"
TITLE_INPUT_SELECTOR = "textarea[placeholder*='제목을 입력하세요'], input[placeholder*='제목']"
BODY_INPUT_SELECTOR = ".se-main-container, .se-content"
PUBLISH_PANEL_BUTTON = "button:has-text('발행')"
CONFIRM_PUBLISH_BUTTON = "button:has-text('발행하기')"

# The state file will reside near this script
STATE_FILE = os.path.join(os.path.dirname(__file__), "state.json")

def process_markdown_content(content: str, is_korean: bool) -> str:
    """
    Process markdown to remove '### Daily Point' sections to avoid compliance issues
    and return the cleaned markdown string.
    """
    # Find the start of ### Daily Point and the start of the next section (like Weekly Schedule)
    # We will remove everything from "### Daily Point" up to but NOT including the next "###" or "##" section.
    # Note: Weekly schedule could be "### Weekly Schedule", "### 주간 일정", etc.
    
    # We remove anything between '### Daily Point' (or similar) up to the next heading
    # To be safe, we just remove the entire Daily Point section.
    
    # regex matches "### Daily Point" or "### 데일리 포인트" up to the next "###" or "##"
    pattern = r"(###\s+(?:Daily Point|데일리 포인트|CIO 코멘트).*?)(?=\n##|\Z)"
    cleaned_content = re.sub(pattern, "", content, flags=re.DOTALL | re.IGNORECASE)
    
    # Add a disclaimer at the end
    disclaimer = "\n\n---\n*Disclaimer: 본 발행물은 정보 제공 및 교육용으로만 제공되며 재무, 투자 또는 법률적 조언을 구성하지 않습니다.*" if is_korean else "\n\n---\n*Disclaimer: The information provided is for informational purposes only and does not constitute financial, investment, or legal advice.*"
    
    return cleaned_content.strip() + disclaimer

def main():
    file_path = os.environ.get("POST_FILE_PATH")
    if not file_path:
        print("Error: POST_FILE_PATH environment variable is not set.")
        sys.exit(1)

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        sys.exit(1)

    print(f"Loaded Markdown: {file_path}")
    is_korean = "_ko.md" in file_path
    
    # Extract date
    date_match = re.search(r"##\s+(\d{2}\s+[A-Za-z]+\s+\d{4})", content)
    post_date = date_match.group(1) if date_match else "Unknown Date"

    # Extract tags
    tags = re.findall(r"[-*]\s+\*\*([^\*]+)\*\*", content)
    tags = tags[:3]
    tags_str = ", ".join(tags)

    if is_korean:
        title = f"{post_date} - 일일 시황 요약 ({tags_str})"
    else:
        title = f"{post_date} - The Daily Tape ({tags_str})"

    # Process and remove compliance-risk sections
    raw_body = process_markdown_content(content, is_korean)

    # Convert to HTML for Clipboard API
    html_content = markdown.markdown(raw_body, extensions=["tables"])
    html_content = html_content.replace("\n", "")

    print(f"Title: {title}")
    print(f"Tags: {tags_str}")
    
    # TODO: Make sure state.json has been generated by manually logging into Naver once.
    with Stealth().use_sync(sync_playwright()) as p:
        if not os.path.exists(STATE_FILE):
            print(f"Warning: State file not found at {STATE_FILE}. Please login manually and save state.json.")

        browser = p.chromium.launch(
            headless=False, # TODO: Set headless=True when running reliably in background
            args=["--disable-blink-features=AutomationControlled", "--no-sandbox"],
        )

        context_args = {}
        if os.path.exists(STATE_FILE):
            context_args["storage_state"] = STATE_FILE
        context = browser.new_context(**context_args, viewport={"width": 1280, "height": 800})
        
        # Grant clipboard-write permission for the origin
        context.grant_permissions(["clipboard-read", "clipboard-write"])
        
        page = context.new_page()

        try:
            print("Navigating to Naver Premium editor...")
            page.goto(NEW_POST_URL)
            page.wait_for_load_state("networkidle")

            print("Entering title...")
            try:
                page.wait_for_selector(TITLE_INPUT_SELECTOR, state="visible", timeout=15000)
                page.fill(TITLE_INPUT_SELECTOR, title)
            except Exception as e:
                print("Could not find title selector, proceeding anyway. Error:", e)

            print("Writing to clipboard and pasting Rich Text...")
            clipboard_injection_js = f"""
            async () => {{
                const blob = new Blob([`{html_content}`], {{ type: 'text/html' }});
                const data = [new ClipboardItem({{ 'text/html': blob }})];
                await navigator.clipboard.write(data);
            }}
            """
            page.evaluate(clipboard_injection_js)

            # Click body and paste
            try:
                page.wait_for_selector(BODY_INPUT_SELECTOR, state="visible", timeout=15000)
                page.click(BODY_INPUT_SELECTOR)
                page.wait_for_timeout(500)
                page.keyboard.press("Meta+V") # Cmd+V on mac, Ctrl+V on windows
                page.wait_for_timeout(2000)
            except Exception as e:
                print("Failed to paste into body:", e)

            print("Publishing...")
            try:
                # TODO: Add logic to set tags and categories in Naver Premium Content here if needed
                page.click(PUBLISH_PANEL_BUTTON)
                page.wait_for_timeout(2000)
                page.click(CONFIRM_PUBLISH_BUTTON)
                page.wait_for_timeout(3000)
                print("Successfully published to Naver Premium!")
            except Exception as e:
                print("Could not complete publish flow automatically:", e)

            if context_args.get("storage_state"):
                context.storage_state(path=STATE_FILE)

        except Exception as e:
            print(f"Failed to publish to Naver Premium: {e}")
            raise e
        finally:
            browser.close()

if __name__ == "__main__":
    main()
